apiVersion: v1
kind: Service
metadata:
  name: springboot-service  # 서비스의 이름

spec:
  type: NodePort            # 외부 접속을 위한 노드포트 방식 사용
  selector:
    app: springboot         # 어떤 파드와 연결할지 (Deployment와 같은 label)
  ports:
    - port: 8080            # 서비스가 열어줄 포트 (클라이언트가 요청 보냄)
      targetPort: 8080      # 파드 내부 컨테이너의 포트
      nodePort: 30080       # 외부에서 접속할 때 사용할 포트